### ISSUE TITLE
Apache 2 -  php 7.2.19 - getting warning / array dump vs loading page

### ISSUE THREAD

**Issue by northtron** [maptiler/tileserver-php#146]
Hi, I'm trying to migrate my tile server to a new server. 
Coming from php 5 / apache setup where everything works ok.

I am using a DigitalOcean ubuntu 18.04 server, have added all the mod_rewrite and header rules in Apache2.SQLite3 is installed on PHP 7.2.19.

I ran the tile check code, and everything came back supported/enabled.
Hitting the site with no .mbtiles file present, I get the normal TileServer page, but showing as empty.  
When I hit the site after adding an .mbtiles to the directory, instead of getting the tile serving page, I appear to be getting back an Array dump that looks like this...  I'm not getting any errors thrown in my log file.. 

`#0 /var/www/html/other/tileserver.php(300): PDO->__construct('sqlite:residenc...', '', '', Array) #1 /var/www/html/other/tileserver.php(186): Server->DBconnect('residences.mbti...') #2 /var/www/html/other/tileserver.php(104): Server->metadataFromMbtiles('residences.mbti...') #3 /var/www/html/other/tileserver.php(536): Server->setDatasets() #4 /var/www/html/other/tileserver.php(1284): Server->getHtml() #5 /var/www/html/other/tileserver.php(18): Router::serve(Array) #6 {main}`

Here are the examples: [array dump with residences.mbtiles](https://tile.northmap.ca/other/)
[tile checker code from these forums showing A-OK](https://tile.northmap.ca/tile-check.php)
[Empty tile server setup with no .mbtiles](https://tile.northmap.ca/parcel/)

**Comment by northtron** [comment]
BAH, I can't believe I was so dumb. I didn't have the right php-sqlite installed. Closing this ticket. Sorry guys
