### ISSUE TITLE
localhost MBTiles

### ISSUE THREAD

**Issue by ethanbyers** [maptiler/tileserver-php#149]
I am able to get to the TileServer page but when I go to localhost/tileserver/folder/file where my MBTiles file is saved within htdocs I get a 403 Error saying "You don't have permission to access the requested object. It is either read-protected or not readable by the server." I also ran a MBTiles reader in Safe Software FME workbench with the file and got errors stating "Failed to obtain any schemas from reader 'MBTILES' from 1 datasets. This may be due to invalid datasets or format accessibility issues due to licensing, dependencies, or module loading." I purchased this map from OpenMapTiles so I don't see why the file wouldn't be working in programs designed for that file type.

**Comment by daliborjanak** [comment]
The tutorial is here https://openmaptiles.org/docs/host/tileserver-php/
Just copy the mbtiles into a folder next to tileserver.php and then open localhost/tileserver-php/ there will be an interface with sample viewers. If this not works, then might be a problem with Apache config or rights for files

**Comment by ethanbyers** [comment]
I have the tileserver folder inside htdocs which allows me to go to localhost/tileserver and land on a page similar to the one expected from the examples. However, once I add  a mbtiles file to the tileserver folder it returns this error on the localhost page

#0 C:\xampp\htdocs\tileserver\tileserver.php(300): PDO->__construct('sqlite:contours...', '', '', Array)
#1 C:\xampp\htdocs\tileserver\tileserver.php(186): Server->DBconnect('contours-2016-1...')
#2 C:\xampp\htdocs\tileserver\tileserver.php(104): Server->metadataFromMbtiles('contours-2016-1...')
#3 C:\xampp\htdocs\tileserver\tileserver.php(536): Server->setDatasets()
#4 C:\xampp\htdocs\tileserver\tileserver.php(1284): Server->getHtml()
#5 C:\xampp\htdocs\tileserver\tileserver.php(18): Router::serve(Array)
#6 {main}

If I put that mbtiles file inside a seperate folder inside tileserver, the error goes away. Then when I go localhost/tileserver/folder/file it returns the 403 error.

Is there any clues as to how to edit the Apache config to fix this?
________________________________

**Comment by prasadrajuv** [comment]
read documentation mbtile is sqlite file need to install phq sqlite module and rewrite and settings for .htaccess
sudo apt-get install -y php7.4-sqlite
sudo a2enmod rewrite
